### ISSUE TITLE
When playing live stream it crashes

### ISSUE THREAD

**Issue by andyching168** [windows-server-2003/ThirdTube#11]
I clicked into one of the live stream in searches
the 3DS will crash
![IMG_20210724_211320](https://user-images.githubusercontent.com/53651198/126869599-90e3faf5-36de-4a0a-9a03-e59491d70c37.jpg)

**Comment by windows-server-2003** [comment]
Okay, the support of live streams is planned in #5.
Crashing is a problem even if it's not supported yet, but it will be fixed when #5 is resolved.

**Comment by windows-server-2003** [comment]
Livestream support is now implemented.
