### ISSUE TITLE
Sound Service Error At Starting The Application

### ISSUE THREAD

**Issue by HugoRed58** [windows-server-2003/ThirdTube#113]
Error code: Could not initialize NDSP (sound service)
Console Edition: Old nintendo 3DS
Console Version: 11.15.0-47U
Console Region: USA
Luma3DS Version: v11.0

**Comment by Fratze64** [comment]
Run this app : https://github.com/zoogie/DSP1/releases

**Comment by HugoRed58** [comment]
@Fratze64 Thank you so much
