### ISSUE TITLE
App crashes when closing 

### ISSUE THREAD

**Issue by Shaughn-david** [windows-server-2003/ThirdTube#12]
I was watching a video and I closed out of the app (pressing the home button then pressing (a)) using new 2ds
![image](https://user-images.githubusercontent.com/76626288/126912433-2bbbe39f-b480-4b71-956e-c31b9f34f77e.jpg)

**Comment by windows-server-2003** [comment]
Could you test the latest release and see if it still occurs with "experimental sslc" enabled ?

**Comment by Shaughn-david** [comment]
I haven’t updated to version 0.1.1 yet but the crashes seem to only happen when the 3ds IP and DNS settings are set to automatic.

**Comment by Shaughn-david** [comment]
I have updated and the crashes still happen when the IP and DNS settings are set to automatic. (Using the experimental sslc)

**Comment by windows-server-2003** [comment]
Okay, I'll continue to investigate it.
By the way, is #13 a seperate issue from this?

**Comment by Shaughn-david** [comment]
It was originally but #13 is so similar to this one. The only difference between #12 and #13 is that 13 is exiting out of the app using the hamburger menu which this issue covers too. So #13 is kind of redundant.

**Comment by men9xuan** [comment]
I got the same issue on new 3ds XL. Happens all the time to me. It happens both when exiting with menu and the home button.

**Comment by windows-server-2003** [comment]
@men9xuan @Shaughn-david 
Can you try v0.4.0 and see if it still happens?

**Comment by Shaughn-david** [comment]
This seems to be fixed

**Comment by Shaughn-david** [comment]
Sometimes it takes a few min to close though

**Comment by windows-server-2003** [comment]
Thank you for testing. I'm closing this issue and #13 for now. Please reopen if the same issue recurs. I'm opening a new issue for the long time of exiting.
