### ISSUE TITLE
Would love to see better performance on the old 3ds.

### ISSUE THREAD

**Issue by Xuser641** [windows-server-2003/ThirdTube#121]
Would love to see better performance on the old 3ds, because (i imagine) a lot of people (including me so i am biased there!) only have an old 3ds, it would be nice if we could get the same performance as the original youtube app.

**Comment by Poketubepoggu** [comment]
Impossible. The new 3DS doesn't even have the speeds of the old YouTube app on new 3DS. The old 3DS could never get a speed that fast because as Windows-Server has stated, he doesn't know how they got it that optimized.

**Comment by Xuser641** [comment]
I reckon they did something on YouTube's end actually...

**Comment by windows-server-2003** [comment]
Hmm, I do not see any further speedup possible currently. In v0.5.1, the font drawing was quickened, so it may contribute to better performances a little bit.
