### ISSUE TITLE
720p support by using the 800px mode (N3DS only feature)

### ISSUE THREAD

**Issue by Paindeluxe** [windows-server-2003/ThirdTube#122]
I do not know If that would be possible as I only see a 1mb/s download on the 3ds but It may work who knows.

This Is the 800px mode I'm referring to --> https://db.universal-team.net/3ds/horihd-gallery

**Comment by windows-server-2003** [comment]
#50 
At least 720p is not possible

**Comment by Paindeluxe** [comment]
Oh well
