### ISSUE TITLE
i got this error message when i tried to play video

### ISSUE THREAD

**Issue by joseowo** [windows-server-2003/ThirdTube#123]
i tried to play a music or video i got this error message from thirdtube. i it affects my brother 3ds too and i reset the wifi router still problem still there can you update the decrypter.
![IMG_20221005_072342](https://user-images.githubusercontent.com/86930732/194205660-0b66e762-d9bc-4564-8cec-94bef9622997.jpg)

**Comment by cooolgamer** [comment]
fixed itself now

**Comment by windows-server-2003** [comment]
Should be fixed now.
