### ISSUE TITLE
Exiting the app from the hamburger menu doesn’t always work and crashes

### ISSUE THREAD

**Issue by Shaughn-david** [windows-server-2003/ThirdTube#13]
It seems to crash while playing videos
![7476A248-3F82-4D70-BE4B-A5C86AA6A90D](https://user-images.githubusercontent.com/76626288/126915187-c0377c84-5439-4933-a971-8836a3459858.jpeg)

**Comment by Shaughn-david** [comment]
Correction: When exiting from the app from the hamburger menu not pressing the home button.

**Comment by windows-server-2003** [comment]
I'm currently not able to reproduce this.
Is it completely random ? Does it happen even if you just open the app, search, play a video, and exit while playing ?
Is it after the playback hangs due to network loading that this happens?

**Comment by Shaughn-david** [comment]
It only crashes when a video is loading, stuck, and playing. Exiting the app using the hamburger menu when a video isn’t playing works fine.

**Comment by windows-server-2003** [comment]
See #12.
