### ISSUE TITLE
some videos completely crashes even if not playing

### ISSUE THREAD

**Issue by cooolgamer** [windows-server-2003/ThirdTube#133]
The app instant crashes when opened after updating to the latest version (v0.5.1)

The fix was to delete 3ds/thirdtube folder but I lost my history and subscriptions...
Hope there's a fix for that

Edit: only deleting the history file fixed it, the problem is the history

**Comment by windows-server-2003** [comment]
Could you post the picture of crash screen(or crash dump file)?

**Comment by cooolgamer** [comment]
ok this seems to happens with a specific (or some others) videos because it even crashes when I pen my playlist even if the problematic video isn't playing
Anyways, here's the crash, hope that helps:
![image](https://user-images.githubusercontent.com/64099608/201718644-1c1538eb-6f7e-47c6-a124-fc463a3e2747.png)

**Comment by cooolgamer** [comment]
Update: it only happens on the .cia version, the .3dsx works fine

**Comment by cooolgamer** [comment]
fixed in v0.5.2
