### ISSUE TITLE
I discovered another bug

### ISSUE THREAD

**Issue by shadow8493** [windows-server-2003/ThirdTube#135]
Whenever i try to rewatch a video my history is completely deleted

**Comment by windows-server-2003** [comment]
In v0.5.2, I implemented a tweak in the app so that it's resistant to data loss.
If this happens again in the new release, please open another issue. In that case, I will probably ask some questions about the content in the file /3ds/ThirdTube/history.json

**Comment by windows-server-2003** [comment]
I apologize for the loss of the history.
