### ISSUE TITLE
(I know i made an issue where you said it won't work, but look...) Support for 60FPS by pre-caching the video (buffer)

### ISSUE THREAD

**Issue by Minionguyjpro** [windows-server-2003/ThirdTube#137]
Isn't there really a way by using some sort of caching to play videos in 60FPS on **New** 3DS? The hardware is better, and i think that games on the New 3DS also run at 60FPS. If they don't, isn't it possible to use an FPS like 40 or 45?

**Comment by windows-server-2003** [comment]
First, I assume you know that there are only 30 FPS option for resolution lower than 720p on YouTube, so we have to use at least 720p for higher FPS.
The CPU & Hardware decoder on New 3DS has the ability to decode a 720p video at the speed of about 15 frames per second(untested but definitely < 30).
Caching is possible, but it means you have to every time wait 10 seconds to see 2 seconds of video at 60 FPS. It can't even play 720p video at 30 FPS without waiting.
Also, every decoded 720p frame eats 2 MB of RAM, so the cache for one second of video eats 120 MB which is almost beyond our usable ram
