### ISSUE TITLE
High resolution mode toggle

### ISSUE THREAD

**Issue by tomrow** [windows-server-2003/ThirdTube#14]
It would be nice if the 800px narrow pixel mode could be toggled instead of always on. It might improve performance and assist in a steady frame rate.

**Comment by windows-server-2003** [comment]
I doubt disabling 800 px mode would improve FPS as 99.9% of the load depends on the resolution of the video, not the screen size.
By the way, do you experience a low frame rate sometimes?

**Comment by windows-server-2003** [comment]
I'm closing this as I'm sure disabling 800 px mode won't improve the framerate.
