### ISSUE TITLE
Crashes, possibly emojis

### ISSUE THREAD

**Issue by code32123** [windows-server-2003/ThirdTube#143]
When looking through comments, viewing a chann, or trying to play a video, the app will crash to a black arm11 debug screen. When viewing the channels that cause crashes kn another device, the troublesome accounts have emojis in the description. Possibly this is what's causing other crashes in comments and videos?
I'm on an old 3DS, let me know if there's any other information you need!

**Comment by CatsLover2006** [comment]
I do agree, this is probably related. I might fork it and remove the text optimizations to try and fix it.
O3DS isn’t officially supported, good luck getting videos to run at full speed.

**Comment by CatsLover2006** [comment]
Actually, this is the same issue as #138, it’s a font drawing issue.

**Comment by JimmySmythe** [comment]
Probably a duplicate, and the fork mentioned there fixes this too. Thanks!

**Comment by code32123** [comment]
Probably a duplicate, the mentioned fork there fixies this too. Thanks!
