### ISSUE TITLE
Suggestion: YouTube Shorts Page

### ISSUE THREAD

**Issue by Poketubepoggu** [windows-server-2003/ThirdTube#153]
Have a button on the main menu to open a YouTube Shorts page.
YouTube Shorts should be rotated 90 degrees so that you hold the DS on its side and loops when the video is over.
The page should take a mix of random shorts from channels you are subscribed to.
Information about the video and channel could be shown on the Touch Screen. Tap the channel to open its channel page in the regular mode. Tap anywhere else on the screen to go to the next video.

**Comment by cooolgamer** [comment]
oh hell nah

**Comment by ZippyZolton** [comment]
oh hell nah
