### ISSUE TITLE
Error in most music videos

### ISSUE THREAD

**Issue by aridsian3000** [windows-server-2003/ThirdTube#180]
when trying to see music videos, whether they are official or unofficial videos, it doesn't even let you see them, it only throws the error

Summary :
[Error] ffmpeg returned NOT success.
Description :
[v] avformat_open_input() failed -1094995529

Place :
Vid/Decode thread
Error Code :
0xfffffffa

the live broadcasts and the videos of normal channels work perfectly but in my case no music video leaves it, it has only worked in some that do not have copyright but usually in none of the music it leaves only tracks of a single or entire song so In addition, the application seems to work perfectly, only the option to log in would be missing, but whether or not there is that option, it would not matter so much.  It would be great if they fixed that problem.
![16904397188023726413719262584533](https://github.com/windows-server-2003/ThirdTube/assets/78612064/f1bf9576-6c1f-46aa-9a78-7febe52a2f14)

**Comment by AverageComet250** [comment]
seems to be linked to music videos... normal videos seem to still work....

**Comment by windows-server-2003** [comment]
Should be fixed. Sorry for long period of unavailability.
