### ISSUE TITLE
Debugging info glitches when you enable it before you play a video

### ISSUE THREAD

**Issue by SleepyBoi2852** [windows-server-2003/ThirdTube#20]
So I was just watching a random video, and it started glitching out, and it crashed. ![image](https://user-images.githubusercontent.com/35126957/127655818-756224c6-7b30-43f1-9d22-9b6005a1b0a5.jpeg)

So I tried again, and I recorded it (sorry for the self promo lol). It didnt crash, but it was pretty interesting.
![video](https://user-images.githubusercontent.com/35126957/127655882-9c94cdda-77b2-4d0c-b3a1-2e3258876d23.MOV)

**Comment by SleepyBoi2852** [comment]
Also no, my internet is not slow. It's pretty fast, and full functionality returns when I turn the debug info off.

**Comment by windows-server-2003** [comment]
I've seen this happen several times while developing this app but don't have a way to reproduce it at a decent rate.
How often can you make this happen?

**Comment by Core-2-Extreme** [comment]
That's because you displayed too much characters/textures.
It seems to the url that in log is too long.
I'm not sure but I think it related to [C2D_DEFAULT_MAX_OBJECTS](https://github.com/windows-server-2003/ThirdTube/blob/main/source/system/draw/draw.cpp#L741)

**Comment by windows-server-2003** [comment]
Thank you for the info,
Most of the long string is not going to be displayed anyway, so I'm just cutting the string into 100 characters or so.

**Comment by windows-server-2003** [comment]
Implemented.
Thank you two for reporting this issue and providing useful information about it !

**Comment by windows-server-2003** [comment]
[ThirdTube.zip](https://github.com/windows-server-2003/ThirdTube/files/6911361/ThirdTube.zip)
If possible, can you test this to confirm it's actually fixed ?

**Comment by SleepyBoi2852** [comment]
> I've seen this happen several times while developing this app but don't have a way to reproduce it at a decent rate.
> How often can you make this happen?

it happens all the time when i have the info open and scroll up

**Comment by SleepyBoi2852** [comment]
Ok. I'll see

**Comment by SleepyBoi2852** [comment]
It works now!

**Comment by windows-server-2003** [comment]
Thank you for testing!

**Comment by SleepyBoi2852** [comment]
Yw
