### ISSUE TITLE
ffmpeg EVERYWHERE

### ISSUE THREAD

**Issue by Janter1603** [windows-server-2003/ThirdTube#214]
I don't know if you're gonna read this but i have been getting the ffmpeg error on every video i click!
This Is Nut's!
can you do something about it

**Comment by TheRealAgentJ** [comment]
I have the same problem

**Comment by TALKjpg** [comment]
Same here

**Comment by VSjnk** [comment]
Me too!
Glad to know I'm not the only one!

**Comment by Nidoskull** [comment]
Fifthing this issue, let's see what Google changed this time

**Comment by Nnamllit1** [comment]
jup i have the same problem

**Comment by OxygenL602** [comment]
Yup, same

**Comment by mimix8317** [comment]
yes i have the same

**Comment by mimix8317** [comment]
now i can't watch video at night :,(

**Comment by Giegue-II** [comment]
same issue
i want to listen to mainly facts guy :(

**Comment by Maxbrick** [comment]
Yet another clone of https://github.com/windows-server-2003/ThirdTube/issues/161

not surprising considering how common the issue is

In short some video formats are not currently supported (oddly enough sometimes i watch a video and later on i watch the same video and it doesn’t work) it has to do with the format availability from YT

**Comment by mimix8317** [comment]
When I launch a video it loads 2 seconds then error ffmpeg it's really annoying...

**Comment by mimix8317** [comment]
problem is for ALL videos sometimes the thirdtube folder gets corrupted in the root folder with the name @-è(

**Comment by Janter1603** [comment]
> problem is for ALL videos sometimes the thirdtube folder gets corrupted in the root folder with the name @-è(

me too I wonder if it's going to get repaired anytime soon

**Comment by Janter1603** [comment]
> Yet another clone of #161
> 
> not surprising considering how common the issue is
> 
> In short some video formats are not currently supported (oddly enough sometimes i watch a video and later on i watch the same video and it doesn’t work) it has to do with the format availability from YT

it strangly works if i restart thirdtube then play the video again (well, when it works..)

**Comment by mimix8317** [comment]
you think the file corruption has something to do with the non-function. the corruption was big because the file was no longer deleted and the date is still 05/31/2099. I removed the corruption but it still doesn't work. I can't wait for it to work again 🤣

**Comment by mimix8317** [comment]
![Uploading 1718800209716827593687266245847.jpg…]()

**Comment by 5GBurrito** [comment]
same, every video, for specificness's sake, it wason a  new 3ds xl

**Comment by CarCrasher13** [comment]
I am also receiving this error, it may be caused by Youtube's new ad blocker blocker thing (Just speculation)

**Comment by Janter1603** [comment]
when do we get to watch funny australia mp3 guy on 3ds again??!!

**Comment by 5GBurrito** [comment]
I can confirm, the one grit does not fix the issue.

**Comment by Janter1603** [comment]
> I can confirm, the one grit does not fix the issue.

what will then? if so, when?

**Comment by SquidSalad69** [comment]
same issue, when did the problem start?

**Comment by Maxbrick** [comment]
From what I can understand the problem is that some yt videos do not have resolutions <480p available, so until the author implements 480p video support, there isn’t really a solution. I could be wrong though.Sent from my iPadOn Jun 24, 2024, at 2:18 PM, Janter ***@***.***> wrote:﻿

I can confirm, the one grit does not fix the issue.

what will then? if so, when?

**Comment by Giegue-II** [comment]
> From what I can understand the problem is that some yt videos do not have resolutions <480p available, so until the author implements 480p video support, there isn’t really a solution. I could be wrong though.Sent from my iPadOn Jun 24, 2024, at 2:18 PM, Janter ***@***.***> wrote:﻿ I can confirm, the one grit does not fix the issue. what will then? if so, when? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

then why dosnt it work when video is off

**Comment by Maxbrick** [comment]
Ig it’s just how YT works, like, the “video file” doesn’t just include the visuals but also the audio too? Or like since YT can’t send the video data it just can’t load period, or maybe the client itself doesn’t support video playback without, well, video. Just speculation, your guess is as good as mine ¯\_(ツ)_/¯On Jun 28, 2024, at 2:54 PM, Giegue-II ***@***.***> wrote:﻿
then why dosnt it work when video is off

**Comment by Janter1603** [comment]
> Ig it’s just how YT works, like, the “video file” doesn’t just include the visuals but also the audio too? Or like since YT can’t send the video data it just can’t load period, or maybe the client itself doesn’t support video playback without, well, video. Just speculation, your guess is as good as mine ¯\_(ツ)_/¯On Jun 28, 2024, at 2:54 PM, Giegue-II ***@***.***> wrote:﻿ then why dosnt it work when video is off —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

it doesnt work no matter what setting i switch on or off, 114, 240, 340p, off, it just doesn't load anything

**Comment by Maxbrick** [comment]
Those videos options are just part of the client. The options, when pressed, request the YT API to provide a video file depending on res u selected. But there is no compatible video file from the YT API. And since the video file is required to play anything (including audio) it just doesn’t load I think?But yeah honestly if I’m being real I’d say just ask someone else lmao I have barely any idea what I’m talking aboutOn Jun 28, 2024, at 9:42 PM, Janter ***@***.***> wrote:﻿

Ig it’s just how YT works, like, the “video file” doesn’t just include the visuals but also the audio too? Or like since YT can’t send the video data it just can’t load period, or maybe the client itself doesn’t support video playback without, well, video. Just speculation, your guess is as good as mine ¯_(ツ)_/¯On Jun 28, 2024, at 2:54 PM, Giegue-II @.> wrote:﻿ then why dosnt it work when video is off —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.>

it doesnt work no matter what setting i switch on or off, 114, 240, 340p, off, it just doesn't load anything

**Comment by Mixarar** [comment]
Doesn't work either here, the same issue FFMPEG on all settings, even videos that are considered soundtracks by youtube (e.g a static picture automatically generated.)

**Comment by Janter1603** [comment]
> Doesn't work either here, the same issue FFMPEG on all settings, even videos that are considered soundtracks by youtube (e.g a static picture automatically generated.)

OMG!!! FURRY, MUST PROTEK ROM ALL HERM!!!
also still not working, :p

**Comment by 5GBurrito** [comment]
> From what I can understand the problem is that some yt videos do not have resolutions <480p available, so until the author implements 480p video support, there isn’t really a solution. I could be wrong though.>

I haven't used the application in a week or two but I don't think this is the issue. I say this because all videos , including videos that worked previously, don't work. This next bit is complete speculation, but the issue may be caused by youtube's battle on adblockers (I have nothing to back this up, its just a guess)

**Comment by Janter1603** [comment]
yup we're dead

**Comment by Janter1603** [comment]
> > From what I can understand the problem is that some yt videos do not have resolutions <480p available, so until the author implements 480p video support, there isn’t really a solution. I could be wrong though.>
> 
> I haven't used the application in a week or two but I don't think this is the issue. I say this because all videos , including videos that worked previously, don't work. This next bit is complete speculation, but the issue may be caused by youtube's battle on adblockers (I have nothing to back this up, its just a guess)

that's what i thought too. :astonished:

**Comment by Janter1603** [comment]
guys there's a dude who made a pretty informative explanation with the current issue going on,
you should check them out
https://github.com/windows-server-2003/ThirdTube/issues/216#issue-2385722217

**Comment by Maxbrick** [comment]
Yeahhhhh… I think we’re all screwed for now ‘till the developer comes back from the dead. Or if someone else makes a fork of this project and implements their own fix.Sent from my iPadOn Jul 1, 2024, at 12:51 PM, Anthony ***@***.***> wrote:﻿

From what I can understand the problem is that some yt videos do not have resolutions <480p available, so until the author implements 480p video support, there isn’t really a solution. I could be wrong though.>

I haven't used the application in a week or two but I don't think this is the issue. I say this because all videos , including videos that worked previously, don't work. This next bit is complete speculation, but the issue may be caused by youtube's battle on adblockers (I have nothing to back this up, its just a guess)

**Comment by Maxbrick** [comment]
Yeah I agreeSent from my iPadOn Jul 2, 2024, at 12:09 PM, Janter ***@***.***> wrote:﻿
guys there's a dude who made a pretty informative explanation with the current issue going on,
you should check them out
#216 (comment)

**Comment by Janter1603** [comment]
> Yeahhhhh… I think we’re all screwed for now ‘till the developer comes back from the dead. Or if someone else makes a fork of this project and implements their own fix.Sent from my iPadOn Jul 1, 2024, at 12:51 PM, Anthony ***@***.***> wrote:﻿ From what I can understand the problem is that some yt videos do not have resolutions <480p available, so until the author implements 480p video support, there isn’t really a solution. I could be wrong though.> I haven't used the application in a week or two but I don't think this is the issue. I say this because all videos , including videos that worked previously, don't work. This next bit is complete speculation, but the issue may be caused by youtube's battle on adblockers (I have nothing to back this up, its just a guess) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Videos Can Be <480p
Look At The Older Video's On Youtube

**Comment by Janter1603** [comment]
My Fellow Issue Dude's
We Have An Even More Detailed One:https://github.com/windows-server-2003/ThirdTube/issues/217
Also, I'm Pretty Sure it's saying "ffmpeg"

**Comment by Maxbrick** [comment]
Yeah I don’t have this issue for every video I load, just a lot of them. But yah ur right there’s still plenty of videos that are supported (at least on my end)Sent from my iPadOn Jul 3, 2024, at 12:50 AM, Janter ***@***.***> wrote:﻿

Yeahhhhh… I think we’re all screwed for now ‘till the developer comes back from the dead. Or if someone else makes a fork of this project and implements their own fix.Sent from my iPadOn Jul 1, 2024, at 12:51 PM, Anthony @.> wrote:﻿ From what I can understand the problem is that some yt videos do not have resolutions <480p available, so until the author implements 480p video support, there isn’t really a solution. I could be wrong though.> I haven't used the application in a week or two but I don't think this is the issue. I say this because all videos , including videos that worked previously, don't work. This next bit is complete speculation, but the issue may be caused by youtube's battle on adblockers (I have nothing to back this up, its just a guess) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.>

Videos Can Be <480p
Look At The Older Video's On Youtube

**Comment by 5GBurrito** [comment]
it's a  shame 
we just gotta wait for the developer
however, imma give it a  shot, i have 0 experience with ffmpg or 3ds homebrew but ill give it a  shot
i encourage those that are even more knowledgabe to give ita shot too
wish me luck and dont get your hopes up too high for this

**Comment by Maxbrick** [comment]
Other than programming in general i also have about 0 experience in 3ds homebrew and ffmpg, so I’m not really one to give advice, but looking into porting code from the (now updated i think?) 3ds video player this app uses would be a good idea probablyOn Jul 12, 2024, at 1:11 AM, Anthony ***@***.***> wrote:﻿
it's a  shame
we just gotta wait for the developer
however, imma give it a  shot, i have 0 experience with ffmpg or 3ds homebrew but ill give it a  shot
i encourage those that are even more knowledgabe to give ita shot too
wish me luck and dont get your hopes up too high for this

**Comment by 5GBurrito** [comment]
ok, so, i'm way utta my depth here, imma keep trying occasionally, but dont rely on me to do it. So, the first thing i tried was to update ffmpeg, the issue with that is that the software uses a  special version of ffmpeg that comnpiles for the 3ds, i'll continue working, but someone with more experience should step in, eventually the creator will come back (hopefully) but lets see if we can fix it before then

**Comment by Maxbrick** [comment]
It’s ok bro, just bullcrap it and hope for the bestSent from my iPadOn Jul 15, 2024, at 11:30 AM, Anthony ***@***.***> wrote:﻿
ok, so, i'm way utta my depth here, imma keep trying occasionally, but dont rely on me to do it. So, the first thing i tried was to update ffmpeg, the issue with that is that the software uses a  special version of ffmpeg that comnpiles for the 3ds, i'll continue working, but someone with more experience should step in, eventually the creator will come back (hopefully) but lets see if we can fix it before then

**Comment by Maxbrick** [comment]
Actually you wanna try making a fix together somehow?Sent from my iPadOn Jul 15, 2024, at 11:30 AM, Anthony ***@***.***> wrote:﻿
ok, so, i'm way utta my depth here, imma keep trying occasionally, but dont rely on me to do it. So, the first thing i tried was to update ffmpeg, the issue with that is that the software uses a  special version of ffmpeg that comnpiles for the 3ds, i'll continue working, but someone with more experience should step in, eventually the creator will come back (hopefully) but lets see if we can fix it before then

**Comment by PaperDrake148** [comment]
> > Yeahhhhh… I think we’re all screwed for now ‘till the developer comes back from the dead. Or if someone else makes a fork of this project and implements their own fix.Sent from my iPadOn Jul 1, 2024, at 12:51 PM, Anthony _**@**_._**> wrote:﻿ From what I can understand the problem is that some yt videos do not have resolutions <480p available, so until the author implements 480p video support, there isn’t really a solution. I could be wrong though.> I haven't used the application in a week or two but I don't think this is the issue. I say this because all videos , including videos that worked previously, don't work. This next bit is complete speculation, but the issue may be caused by youtube's battle on adblockers (I have nothing to back this up, its just a guess) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: _**@**_.**_>
> 
> Videos Can Be <480p Look At The Older Video's On Youtube

Yeahh... Resolution is definitely not the issue. just checked with videos i have confirmed have 144p versions available, and it still does not work.

**Comment by WinRWCG5Fan** [comment]
> > Yet another clone of #161
> > not surprising considering how common the issue is
> > In short some video formats are not currently supported (oddly enough sometimes i watch a video and later on i watch the same video and it doesn’t work) it has to do with the format availability from YT
> 
> it strangly works if i restart thirdtube then play the video again (well, when it works..)

I tried this, and it doesn't work.

**Comment by WinRWCG5Fan** [comment]
Maybe ffmpeg tries to open or decode something on Youtube's servers but it can't.

**Comment by Janter1603** [comment]
Welp, Guess We're Dead

**Comment by 5GBurrito** [comment]
> Actually you wanna try making a fix together somehow?
I mean I'm down, we can just use github, but so far I've made 0 progress, I've just kinds looked at ffmpeg code trying to figure it out but most of it goes right over my head.

**Comment by mimix8317** [comment]
Yes is a great ideo

**Comment by mimix8317** [comment]
Idea

Le mer. 7 août 2024, 10:26, Emilien Andreotti ***@***.***> a
écrit :

> Yes is a great ideo
>

**Comment by SeveringHams** [comment]
The error thrown, `avformat_open_input() failed -1094995529` seems to be returned/thrown by the demuxer in FFmpeg, just looking at the documentation at https://ffmpeg.org/doxygen/trunk/group__libavf.html 

The only mentions of this error anywhere on Google (by searching `"avformat_open_input failed -1094995529"` WITH the quotes) are on Chinese websites, and the one English translated one says to enable the demuxer library, or indicate in the configuration what demuxer library to use, or something to that effect.

Here is the website I found this on: https://programmersought.com/article/89887525290/ It is under the header "Encounter Problems"

The `build.txt` file in `/library/FFmpeg/` tells us that many features of FFmpeg are configured to be disabled on the custom build of FFmpeg used in ThirdTube, and a handful of formats are selected to be enabled, so perhaps reconfiguring it to enable YouTube's current video file format (whatever it may be) would make it work.

I myself could not figure out how to get it to reconfigure and recompile, so maybe someone more experienced than measly me could crack the case.

Just my two cents, but that's what I could find on the matter.

**Comment by mimix8317** [comment]
Oh yes thank you

Le mer. 7 août 2024, 21:32, SeveringHams ***@***.***> a
écrit :

**Comment by 5GBurrito** [comment]
tysm hams, now we have a lead on how to solve the issue, ill try and impliment it when i have some time (mabye this week?)

**Comment by 5GBurrito** [comment]
ok, so i tried to updave the libavformat library which is where remuxing file supposedly are, after struggling to install packages for an hour, and it wouldnt compile, after much struggling, I attempted to compile the vanilla repo and it still didn't compile, attatched is the error on when i compile either the vanilala one or the one with my modifications. any input would be greatly appreciated but i'm done for tonight

[output.log](https://github.com/user-attachments/files/16667836/output.log):
```/media/nvme/FourthTube/source/system/fake_pthread.cpp: In function 'int pthread_mutex_lock(pthread_mutex_t*)':
/media/nvme/FourthTube/source/system/fake_pthread.cpp:35:32: error: request for member 'normal' in '* mutex', which is of non-class type 'pthread_mutex_t' {aka 'long unsigned int'}
   35 |         LightLock_Lock(&mutex->normal);
      |                                ^~~~~~
/media/nvme/FourthTube/source/system/fake_pthread.cpp: In function 'int pthread_mutex_trylock(pthread_mutex_t*)':
/media/nvme/FourthTube/source/system/fake_pthread.cpp:39:45: error: request for member 'normal' in '* mutex', which is of non-class type 'pthread_mutex_t' {aka 'long unsigned int'}
   39 |         int res = LightLock_TryLock(&mutex->normal);
      |                                             ^~~~~~
/media/nvme/FourthTube/source/system/fake_pthread.cpp: In function 'int pthread_mutex_unlock(pthread_mutex_t*)':
/media/nvme/FourthTube/source/system/fake_pthread.cpp:43:34: error: request for member 'normal' in '* mutex', which is of non-class type 'pthread_mutex_t' {aka 'long unsigned int'}
   43 |         LightLock_Unlock(&mutex->normal);
      |                                  ^~~~~~
/media/nvme/FourthTube/source/system/fake_pthread.cpp: In function 'int pthread_mutex_init(pthread_mutex_t*, const pthread_mutexattr_t*)':
/media/nvme/FourthTube/source/system/fake_pthread.cpp:47:32: error: request for member 'normal' in '* mutex', which is of non-class type 'pthread_mutex_t' {aka 'long unsigned int'}
   47 |         LightLock_Init(&mutex->normal);
      |                                ^~~~~~
/media/nvme/FourthTube/source/system/fake_pthread.cpp: In function 'int pthread_once(pthread_once_t*, void (*)())':
/media/nvme/FourthTube/source/system/fake_pthread.cpp:62:54: error: 'struct pthread_once_t' has no member named 'status'
   62 |                 val = __ldrex((s32 *) &once_control->status);
      |                                                      ^~~~~~
/media/nvme/FourthTube/source/system/fake_pthread.cpp:65:49: error: 'struct pthread_once_t' has no member named 'status'
   65 |         } while (__strex((s32 *) &once_control->status, val));
      |                                                 ^~~~~~
/media/nvme/FourthTube/source/system/fake_pthread.cpp:69:31: error: 'struct pthread_once_t' has no member named 'status'
   69 |                 once_control->status = PTHREAD_ONCE_FINISHED;
      |                               ^~~~~~
/media/nvme/FourthTube/source/system/fake_pthread.cpp: In function 'int pthread_cond_init(pthread_cond_t*, const pthread_condattr_t*)':
/media/nvme/FourthTube/source/system/fake_pthread.cpp:77:41: error: request for member 'cond' in '* cond', which is of non-class type 'pthread_cond_t' {aka 'long unsigned int'}
   77 |         CondVar_Init((CondVar *) &cond->cond);
      |                                         ^~~~
/media/nvme/FourthTube/source/system/fake_pthread.cpp: In function 'int pthread_cond_wait(pthread_cond_t*, pthread_mutex_t*)':
/media/nvme/FourthTube/source/system/fake_pthread.cpp:81:41: error: request for member 'cond' in '* cond', which is of non-class type 'pthread_cond_t' {aka 'long unsigned int'}
   81 |         CondVar_Wait((CondVar *) &cond->cond, &mutex->normal);
      |                                         ^~~~
/media/nvme/FourthTube/source/system/fake_pthread.cpp:81:55: error: request for member 'normal' in '* mutex', which is of non-class type 'pthread_mutex_t' {aka 'long unsigned int'}
   81 |         CondVar_Wait((CondVar *) &cond->cond, &mutex->normal);
      |                                                       ^~~~~~
/media/nvme/FourthTube/source/system/fake_pthread.cpp: In function 'int pthread_cond_signal(pthread_cond_t*)':
/media/nvme/FourthTube/source/system/fake_pthread.cpp:86:43: error: request for member 'cond' in '* cond', which is of non-class type 'pthread_cond_t' {aka 'long unsigned int'}
   86 |         CondVar_Signal((CondVar *) &cond->cond);
      |                                           ^~~~
/media/nvme/FourthTube/source/system/fake_pthread.cpp: In function 'int pthread_cond_broadcast(pthread_cond_t*)':
/media/nvme/FourthTube/source/system/fake_pthread.cpp:90:46: error: request for member 'cond' in '* cond', which is of non-class type 'pthread_cond_t' {aka 'long unsigned int'}
   90 |         CondVar_Broadcast((CondVar *) &cond->cond);
      |                                              ^~~~```

**Comment by werwolf2303** [comment]
Weird. I just compiled it a few weeks ago and it produced a cia and 3dsx. Which operating system are you using?

**Comment by werwolf2303** [comment]
I guess linux from the logs. In that case what distro?

**Comment by 5GBurrito** [comment]
Completely forgot to mention this y'all fourthtube is live, it works and were adding features, https://github.com/erievs/FourthTube

**Comment by Janter1603** [comment]
welp it's been fun
