### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by SleepyBoi2852** [windows-server-2003/ThirdTube#29]
There is a grammatical error on "Use experimental sslc" it is the "Restart to apply" text. Instead of saying that, it says "Restart the apply" ![image](https://user-images.githubusercontent.com/35126957/129425312-9f1106c2-0023-4695-8a28-2385b86f7c85.jpeg)

**Comment by windows-server-2003** [comment]
My bad. I'll fix it.
