### ISSUE TITLE
ThirdTube For Old3DS

### ISSUE THREAD

**Issue by ErgFox9** [windows-server-2003/ThirdTube#30]
Youtube for 3ds official: N3DS and O3DS

ThirdTube: N3DS...

poople with N3DS:30%  poople with O3DS:70%

pls create thirdtube for old :(((((

**Comment by ErgFox9** [comment]
yes!

**Comment by ErgFox9** [comment]
or remove error "you don' t have n3ds"


pls

**Comment by windows-server-2003** [comment]
I considered and tested again, but for the reason stated in README, I am not going to support old 3DS.
I understand there is a demand for a YouTube client on 3DS, but old 3DS's performance is so deficient that I'm rather wondering how Google could provide an app that can play YouTube videos at decent frame rate on it.

**Comment by wuniversales** [comment]
Lowering the video quality to 480p could not be played? 
You do not need much quality, on small screens videos with low quality look very good. 
If there are video players for 3ds Old, why doesn't it work with youtube?

**Comment by g3yt** [comment]
What about 24 fps?

**Comment by saku-bruh** [comment]
> In fact, it can't play 144p at a stable rate of 30 FPS. (and even the new 3DS version is playing videos at 360p) Yes, there's a video player for 3ds, but that's what this app uses internally and it says it can barely play H264 (which is what YouTube uses) at 30 FPS.

You should remove that block and just replace it with "You will have a horrible experience get a New 3DS" lol

**Comment by saku-bruh** [comment]
> What about 24 fps?

Nope i think O3DS if it will come (most likely not is going to be 144p only) at 240p the fps drops to 15! But for the N3DS 480p is definitely possible as it is already introduced in the Video player for 3DS by Core2Extreme which this app is based on
![Screenshot_20211105-014133_Bromite](https://user-images.githubusercontent.com/67262050/140435207-b7da29bc-9fb8-4329-b4f2-65c7d104c5e4.png)

**Comment by JustScratchCoder** [comment]
Hello People i am at least trying to get this youtube app to work on old models. I disabled the new 3ds lock. But the video playback is broken. It just displayes some weird lines and crashes randomly. And sometimes the icons turn into colored squares
![IMG_20211107_124939](https://user-images.githubusercontent.com/85436576/140643718-81098f63-ddc2-4b0e-9ba4-293c61560691.jpg)

**Comment by saku-bruh** [comment]
> 
> 
> Hello People i am at least trying to get this youtube app to work on old models. I disabled the new 3ds lock. But the video playback is broken. It just displayes some weird lines and crashes randomly. And sometimes the icons turn into colored squares (The lines display even in channel or video select) ![IMG_20211107_124939](https://user-images.githubusercontent.com/85436576/140643718-81098f63-ddc2-4b0e-9ba4-293c61560691.jpg)

Could we have a video this seems interesting maybe its cause of the crappier specs of the O3DS and it cant handle video playback? Idk but the offline video player plays videos fine since i posted that chart from the video player this app is based on... Strange

**Comment by JustScratchCoder** [comment]
> Could we have a video this seems interesting maybe its cause of the crappier specs of the O3DS and it cant handle video playback? Idk but the offline video player plays videos fine since i posted that chart from the video player this app is based on... Strange

Well propably we could have playback. i just need to look around the code more and mess around with the network decoder

**Comment by saku-bruh** [comment]
> > Could we have a video this seems interesting maybe its cause of the crappier specs of the O3DS and it cant handle video playback? Idk but the offline video player plays videos fine since i posted that chart from the video player this app is based on... Strange
> 
> Well propably we could have playback. i just need to look around the code more and mess around with it

I posted a screenshot above and the O3DS runs 144p at 30fps and going above will just kill the framerate

**Comment by JustScratchCoder** [comment]
> > > Could we have a video this seems interesting maybe its cause of the crappier specs of the O3DS and it cant handle video playback? Idk but the offline video player plays videos fine since i posted that chart from the video player this app is based on... Strange
> > 
> > 
> > Well propably we could have playback. i just need to look around the code more and mess around with it
> 
> I posted a screenshot above and the O3DS runs 144p at 30fps and going above will just kill the framerate

Well there are other codecs to try like MPEG1, MPEG2, H263. But somehow only H264 converts with sound.

**Comment by saku-bruh** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/85436576/140964645-6875ecf9-3f94-4b81-a21f-80532d51d356.png) i just found this line of code. maybe i will modify it just to see if other codecs work better here.

h264 is the most efficient out off all of them try experimenting until you can force the app to use h264 maybe we can get atleast 30fps at 144p out of it

**Comment by JustScratchCoder** [comment]
> > ![image](https://user-images.githubusercontent.com/85436576/140964645-6875ecf9-3f94-4b81-a21f-80532d51d356.png) i just found this line of code. maybe i will modify it just to see if other codecs work better here.
> 
> h264 is the most efficient out off all of them try experimenting until you can force the app to use h264 maybe we can get atleast 30fps at 144p out of it

It seems that third tube uses the one of oldest versions of video player. the 1.1.0.   if i could try implenting the newest one with all of new codecs, 1.4.0 we can get stable 30fps at 144p. or even more, depending on the codec

**Comment by saku-bruh** [comment]
> 
> 
> > > ![image](https://user-images.githubusercontent.com/85436576/140964645-6875ecf9-3f94-4b81-a21f-80532d51d356.png) i just found this line of code. maybe i will modify it just to see if other codecs work better here.
> > 
> > 
> > h264 is the most efficient out off all of them try experimenting until you can force the app to use h264 maybe we can get atleast 30fps at 144p out of it
> 
> It seems that third tube uses the one of oldest versions of video player. the 1.1.0. if i could try implenting the newest one with all of new codecs, 1.4.0 we can get stable 30fps at 144p. or even more, depending on the codec ![image](https://user-images.githubusercontent.com/85436576/141101739-99792fd1-3b3c-4e8c-810e-5124eaf284e3.png) (just jokin, i am not a programmer, i will just wait for windows-server to implement it then we can maybe do something)

1.1.0 sucks ass honestly it only has japanease support and its not optimized as well as 1.4.0

**Comment by JustScratchCoder** [comment]
![image](https://user-images.githubusercontent.com/85436576/152761935-38ebff66-6638-46bd-b542-3f5562471bd3.png)
![20220207_103047](https://user-images.githubusercontent.com/85436576/152761954-1c42ccc1-a552-4d26-b2de-e3c0839a507b.jpg)
coming back after  3 months xD, thank you for the help arm11 and win server.

**Comment by wuniversales** [comment]
Has the old3ds been able to play youtube videos?
Is it going to be implemented in future versions?

**Comment by JustScratchCoder** [comment]
https://www.youtube.com/watch?v=Nc0IATYXBv8 somehow... someone ported thirdtube to old3ds, and the video playback. works great.

**Comment by wuniversales** [comment]
I should have opened PR, instead of leaving those of us who use o3ds wanting hahaha
@windows-server-2003 Any idea how he did it?
