### ISSUE TITLE
60fps video support?

### ISSUE THREAD

**Issue by g3om3tryYT** [windows-server-2003/ThirdTube#37]
I know this isn't supported on youtube at all but because this is a scaper do you link you could get 144p/240p 60fps? Thanks!

**Comment by windows-server-2003** [comment]
Unfortunately, YouTube virtually only offers 60 FPS videos with 720p+ resolutions.
I've looked at the list of available stream types for several videos, but I couldn't find any 60 FPS stream with a resolution that 3DS could possibly handle.
