### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SepticRedhead** [windows-server-2003/ThirdTube#46]
How about a login setup so you can have a account, a homepage and a auto play feature.

**Comment by SleepyBoi2852** [comment]
I think that's a Great Idea, Though That Might be hard to implement.

**Comment by windows-server-2003** [comment]
Unfortunately, I have decided not to implement a login feature.
The main reason is the fear of a ban on your Google account. This app is violating the ToS of YouTube in the first place, so it's possible that accounts used with this app get banned. The main idea of this app is that as long as we don't login with this app, there can be no penalty.

**Comment by Shaughn-david** [comment]
What part of the terms of service does ThirdTube violate?

**Comment by saku-bruh** [comment]
> **Permissions and Restrictions**
> 
> ```
> 2. circumvent, disable, fraudulently engage with, or otherwise interfere with any part of the Service (or attempt to do any of these things), including security-related features or features that (a) prevent or restrict the copying or other use of Content or (b) limit the use of the Service or Content;
> ```
> 
> I think this explicitly forbids direct access to the stream.

Youtube Vanced has login through microG you can try to add that! I use Vanced daily with my google account and i haven't got banned neither has anyone using apps with microG
