### ISSUE TITLE
Build in Equalizer

### ISSUE THREAD

**Issue by werwolf2303** [windows-server-2003/ThirdTube#55]
(Sorry for my bad english)
Can you add a equalizer that the speakers can go over 100%, please

**Comment by windows-server-2003** [comment]
Volume adjuster is implemented in v0.4.0.
Full equalizer is still to be implemented.

**Comment by saku-bruh** [comment]
> Volume adjuster is implemented in v0.4.0. Full equalizer is still to be implemented.

Would be nice to have convolver support as well.

**Comment by windows-server-2003** [comment]
Implemented in v0.5.0
You can access it from the Playback tab.

**Comment by saku-bruh** [comment]
> Implemented in v0.5.0 You can access it from the Playback tab.

cool
