### ISSUE TITLE
Music mode while console is closed

### ISSUE THREAD

**Issue by saku-bruh** [windows-server-2003/ThirdTube#59]
I was thinking if we disable the video option in the quality settings and close the 3DS it should keep playing sort of like a music only mode and it will play on the speakers/headphones? Is this possible?

**Comment by windows-server-2003** [comment]
Implemented in v0.4.0.
However, there seems to be no way to make it play on the speaker while the lid is closed, so it's headphone only.

**Comment by saku-bruh** [comment]
> Implemented in v0.4.0. However, there seems to be no way to make it play on the speaker while the lid is closed, so it's headphone only.

and sleep mode is disabled as well? battery drain was bad enough on 0.3.0 should be a toggle probably for battery life ofc
