### ISSUE TITLE
Option to turn off bottom screen while playing non/fullscreen videos

### ISSUE THREAD

**Issue by saku-bruh** [windows-server-2003/ThirdTube#60]
Keeping the bottom screen on on longer videos is just a waste of battery life could there be a button to turn the bottom screen off or can you only turn both screens off at once not just one?

**Comment by windows-server-2003** [comment]
You can now manually turn of the bottom screen by pressing SELECT + START in v0.5.0
I decided to not implement auto turn off because that would also turn the screen of while you are reading comments, etc.
