### ISSUE TITLE
Login via microG

### ISSUE THREAD

**Issue by Poketubepoggu** [windows-server-2003/ThirdTube#61]
YouTube Vanced uses login via microG, it's unofficial and no one has gotten banned, so login can be implemented using this

**Comment by saku-bruh** [comment]
Yes! I was thinking the same thing I am quite interested if he will implement this how will he implement it? As far as i know microG is Android only but maybe it could work somehow? Would love to have my online subscriptions sync with my 3DS

**Comment by windows-server-2003** [comment]
I searched a bit, and it seems like some people got banned using Vanced fairly recently(several months ago).
Currently, I think the risk of getting banned is too high.

**Comment by saku-bruh** [comment]
> I searched a bit, and it seems like some people got banned using Vanced fairly recently(several months ago). Currently, I think the risk of getting banned is too high.

What? Where??? I have been using Vanced and YT Music for years with no issues

**Comment by saku-bruh** [comment]
Here is a few threads I found and people never had any issues and some comments are recent https://www.reddit.com/r/ApksApps/comments/p9v9cx/youtube_vanced_bans/

https://www.reddit.com/r/Piracy/comments/cphkn3/does_google_ban_youtube_vanced_users/

As I said I had no issues with Vanced which uses microG as the login app and it's just fine Google doesn't care and plus you can just not login at all I think it's worth adding just for that reason

**Comment by windows-server-2003** [comment]
I know this is a way that gives me biased information, but if you search "vanced account ban", you will get some people saying their account got banned possibly because they used Vanced.
There would definitely be someone who uses his main account in ThirdTube, so I do not want to take the risk of it.

**Comment by saku-bruh** [comment]
> biased information
???? What? How am i biased I gave you my reason and some reddit threads threads in which reported bans the least you could have done is gave me links. yet you call me biased for telling you , that you could have been wrong on slightly mistaken... well pardon me then i guess im wrong then.

**Comment by windows-server-2003** [comment]
I meant that if I searching "vanced account ban", I would probably see people who got banned than those who didn't, so I didn't mean to say your argument was biased. Sorry for misleading expression.
What I want to say is that at least some people insist that they got their account banned, so I can't just add that feature without hesitation.

**Comment by windows-server-2003** [comment]
So I would like you to look at the search result of "vanced account ban".

**Comment by saku-bruh** [comment]
> So I would like you to look at the search result of "vanced account ban".

Literally first result i got was basically "Its not the fault with microG or vanced OP mustve commented or did something against the TOS" 
literally first google result i got https://www.reddit.com/r/Vanced/comments/i0m8fb/othermy_youtube_account_was_banned_today/

**Comment by saku-bruh** [comment]
> > So I would like you to look at the search result of "vanced account ban".
> 
> Literally first result i got was basically "Its not the fault with microG or vanced OP mustve commented or did something against the TOS" literally first google result i got https://www.reddit.com/r/Vanced/comments/i0m8fb/othermy_youtube_account_was_banned_today/

Plus i am scratching my head at why you couldnt add a warning message before logging in then people would know what they are "risking" their accounts (to put it in ur terms) then it would solve both issues while introducing google login for convenient login. Seems like the best option imho.

**Comment by saku-bruh** [comment]
> So I would like you to look at the search result of "vanced account ban".

Ok so a coulple of months later I'm looking into it again and did you mean this ? https://www.reddit.com/r/Vanced/comments/oo2e8p/youtube_banned_my_account_for_using_vanced_i_woke/ yeah just him that got banned and he probably lied about it and recently Vanced shut down but.. microG/Vanced users arent being banned they never were actually Google just shut them down and now they wont update the app anymore I'd say you just integrate microG until it stops working cause atm the app is alot like NewPipe
