### ISSUE TITLE
SUGGESTION: Support for other Codecs like MPEG1, MPEG2, H263 etc. 

### ISSUE THREAD

**Issue by JustScratchCoder** [windows-server-2003/ThirdTube#63]
So the video player ThirdTube uses had an update and is there a way to implement decoding to other codecs, this could bring at least some support for O3DS`es.
![image](https://user-images.githubusercontent.com/85436576/141155869-e81c42eb-bf7f-46d9-a69d-00f4ed14591c.png)
![image](https://user-images.githubusercontent.com/85436576/141155898-a989fa51-69c5-4350-a4d8-4814bae17998.png)
![image](https://user-images.githubusercontent.com/85436576/141155918-73a03526-d5f6-45cf-a726-1f3bab7a9acc.png)

Is there a way to implement it?

**Comment by saku-bruh** [comment]
> So the video player ThirdTube uses had an update and is there a way to implement decoding to other codecs, this could bring at least some support for O3DS`es. ![image](https://user-images.githubusercontent.com/85436576/141155869-e81c42eb-bf7f-46d9-a69d-00f4ed14591c.png) ![image](https://user-images.githubusercontent.com/85436576/141155898-a989fa51-69c5-4350-a4d8-4814bae17998.png) ![image](https://user-images.githubusercontent.com/85436576/141155918-73a03526-d5f6-45cf-a726-1f3bab7a9acc.png)
> 
> Is there a way to implement it?

Pretty sure he just needs to implement 1.4.0 and it "should" work

**Comment by windows-server-2003** [comment]
I can support those codecs, but they are not used for YouTube videos.
In [this page](https://gist.github.com/AgentOak/34d47c65b1d28829bb17c24c04a0096f), you can see that YouTube only uses H.264, VP9, AV1 for video and AAC and Opus for audio.
ThirdTube currently supports H.264, AAC, and Opus, and I will not implement VP9 and AV1 for the following reasons.

 - It is said that decoding VP9 and AV1 needs an even faster CPU than H.264
 - We cannot use the HW decoder of the 3ds to decode them as it only supports H.264
 - The library setup for VP9 and AV1 was a mess (I tried but gave up)
