### ISSUE TITLE
Sound mute button?

### ISSUE THREAD

**Issue by Minionguyjpro** [windows-server-2003/ThirdTube#65]
Add an sound mut button.
Sorry if this already exists...

**Comment by windows-server-2003** [comment]
Why don't you just pull the volume slider all the way down?

**Comment by Minionguyjpro** [comment]
Is there an slider?

**Comment by Minionguyjpro** [comment]
I mean i have the software but it's already a month ago since i used it for latest.

**Comment by windows-server-2003** [comment]
I meant the hardware volume slider.

**Comment by Minionguyjpro** [comment]
Oh yeah that's true

**Comment by Minionguyjpro** [comment]
You have Discord?

**Comment by windows-server-2003** [comment]
Yes, the invitation link is in the README.
