### ISSUE TITLE
HOME Menu notification for a new video from a subscribed channel

### ISSUE THREAD

**Issue by Minionguyjpro** [windows-server-2003/ThirdTube#68]
Make it possible to get an HOME Menu notification for a new video from a subscribed channel. I don't know of this can be implemented.

**Comment by windows-server-2003** [comment]
It's possible to send homemenu notifications while the app is opened, but we can't do anything unless the app is opened.
If it's possible, it would be something like modding luma3ds, which I'm not currently considering to do.
