### ISSUE TITLE
No Video's loading

### ISSUE THREAD

**Issue by trextaco9** [windows-server-2003/ThirdTube#75]
Basically I've been using this 2ds xl and i tried thirdtube and when it tries to load a video i get the error saying ffmpeg returned not success

anyone got a solution?

**Comment by windows-server-2003** [comment]
Could you give me the link of a video that it fails to load?

**Comment by trextaco9** [comment]
It fails when trying any video

**Comment by windows-server-2003** [comment]
Can you press SELECT and give me the content of the blue debug log.

**Comment by trextaco9** [comment]
mvdstdlnit ok at 15 mb
Util File save to file  [success] 
deep fail: url use bad/illegal format or missing url
no slash in content range response header
then read beyond eof a lot of times
network decoder init    ffmpeg returned not success [video] avformat
deinit complete

**Comment by windows-server-2003** [comment]
Okay, I spotted the isssue. YouTube just did something on one of their javascripts. I'm going to release a patch soon.

**Comment by windows-server-2003** [comment]
Please try v0.4.1 which I just released

**Comment by trextaco9** [comment]
it worked, thank you
