### ISSUE TITLE
Error 0xfffffffa when I want play a video

### ISSUE THREAD

**Issue by Tomtom67170** [windows-server-2003/ThirdTube#76]
When I want to play a video with Third Tube, I have an screen on the down screen, a blue window with an error and say:"[video] avformat_open_input() failed - 1094995529
" with an error code 0xfffffffa! I can't read the video, this window propose me 2 options:
OK(A) or SAVE (X)!
I tried to reinstall the software but It's not working!
How I Can Fix This?

**Comment by windows-server-2003** [comment]
If you've updated to v0.4.1 and still have problems, please press SELECT and give me the debug log shown.

**Comment by Tomtom67170** [comment]
Oh, it's good, I updated the software to v0. 4.1 and it works better! Thank you

**Comment by NoName0174** [comment]
Hi! I have the same issue, and it doesn't seem to work. I have updated to the latest version, 5.4. 
![IMG_20240712_204337](https://github.com/user-attachments/assets/82845aca-92ac-4db1-8eac-da3408a58cd1)

**Comment by Aleccoool3** [comment]
![IMG_20240714_082726815_HDR](https://github.com/user-attachments/assets/18892a40-bab4-4222-bfa8-81fe3aa6776d)

**Comment by JK-Cookie** [comment]
Hi, I'm also having this problem. First, how do you update it?

**Comment by JK-Cookie** [comment]
Hi, I'm also having this problem but my app is also up to date and I do not knpw how to fix it
