### ISSUE TITLE
QR Code In README To Install Remotely And Directly

### ISSUE THREAD

**Issue by Minionguyjpro** [windows-server-2003/ThirdTube#79]
I already made one. Use these:

PNG:
![ThirdTube QR Code PNG](https://user-images.githubusercontent.com/66115754/153711980-f5be59b1-b58d-439c-9c44-44be9c377445.png)
SVG:
![ThirdTube QR Code SVG](https://user-images.githubusercontent.com/66115754/153711982-24ef7f09-2cd7-46e2-b7c5-8b5a9bbf15fc.svg)

**Comment by windows-server-2003** [comment]
I added it to the README, thank you!

**Comment by Minionguyjpro** [comment]
> I added it to the README, thank you!

@windows-server-2003 You don't need to worry you need to update that link. It automatically downloads the latest release from http://github.com/windows-server-2003/ThirdTube/releases/latest/download/ThirdTube.cia
As long as you keep the CIA calling ``ThirdTube.cia`` in the releases, the QR will keep working.
