### ISSUE TITLE
Many new features and options

### ISSUE THREAD

**Issue by Minionguyjpro** [windows-server-2003/ThirdTube#82]
I have many ideas, i will list them here:
- Slider to change video contrast
- Possibility to set custom button shortcuts for all the Nintendo buttons
- Possibility to switch tabs (General, Comments, Playback) With L button to left tab and R button to right tab
- Support to play video's reversed
- Support to set custom amount of seconds backward and forward uses with these buttons.
- Sharpen effect option

**Comment by windows-server-2003** [comment]
Thank you for the suggestions, but could you please separate the issue?
Here are some reasons :
 - When we finished dealing with one of the issues, we can close the corresponding issue
 - In this kind of issue, another person often comes up and also writes his/her own ideas so the issue never gets closed
 - We can avoid people talking about many different things in one thread

It's completely fine that one person opens twenty issues if they are different ones.
In this case, I think you can merge the second, third and fifth one(titled like "Advanced shortcuts"). By the way, you can skip 10 seconds by pressing d-pad left/right.
Maybe "sharpen effect" and "contrast" can also be merged as they are both about a new video filter.

**Comment by Minionguyjpro** [comment]
I think i unserstand you. I will do this right now.

**Comment by Minionguyjpro** [comment]
Moved to #83 and #84
