### ISSUE TITLE
Add GitHub Actions support for Daily Builds

### ISSUE THREAD

**Issue by Rix565** [windows-server-2003/ThirdTube#85]
So that general users like me can test the latest experimental builds of ThirdTube to see new features & report bugs without having to install 3DS development tools to build it and test it. (makes debugging more easy for these builds & make well bug-fixed builds)

**Comment by Minionguyjpro** [comment]
Agree

**Comment by Minionguyjpro** [comment]
So add an option to auto-update to the nightly build to the latest at startup or from the settings or something in the 3 lines menu.

**Comment by windows-server-2003** [comment]
Github Action should now build .cia and .3dsx every time I push new commits to the main branch
