### ISSUE TITLE
[development version] Some videos are slow down

### ISSUE THREAD

**Issue by Rix565** [windows-server-2003/ThirdTube#89]
On certains videos, not sure why, the FPS of the video start dropping to 2-3 FPS.

This is really disturbing as it ruins the experience.

Please fix it ASAP.

**Comment by windows-server-2003** [comment]
I've just pushed some new commits, so please try the latest one.
If the problem continues:
 - Does it happen with o3ds or n3ds?
 - Does it always occur with a specific video? If so, please give me the link of the video.

**Comment by Rix565** [comment]
Thank, it is now fixed.(now I like more the dev version than the current 0.4.1 lol)
