### ISSUE TITLE
[Feature Request] Return YouTube Dislike implementation

### ISSUE THREAD

**Issue by CSab6482** [windows-server-2003/ThirdTube#91]
I'm not sure if this would be possible, but Vanced (RIP) has the extension built in and it works quite nicely.

https://github.com/Anarios/return-youtube-dislike

**Comment by windows-server-2003** [comment]
Sorry, I do not think this fits well with this app.
ThirdTube is (at least originally) a web-scraping version of browser YouTube, so I do not prefer integrating third-party services.
The dislike count it provides gets inaccurate as time passes anyway.
