### ISSUE TITLE
[Bug] The bottom screen doesn't seem to update when a video is autoplayed

### ISSUE THREAD

**Issue by CSab6482** [windows-server-2003/ThirdTube#93]
I was watching [Mr Beast Squid Game Review](https://youtu.be/sA2bR0BRfVY), a video from PewDiePie that has a 19:06 duration. However, after the video ended, it autoplayed [Kids Decide Who Gets $1000 Is Very Cringe...](https://youtu.be/KC0DlJza3dk), a different video that runs for 33:21. The video on the top screen and the scrubber all the way at the bottom both updated, but everything else still retained the information from the previous video.
![ThirdTube](https://user-images.githubusercontent.com/53708281/164538556-51851401-82b4-4280-820c-54c655528765.png)

I thought that hitting the reload button would reload the information from the current video, but only the Suggestions and Playback tabs updated, with everything else remaining the same.

I am not sure if the autoplay functionality is consequential or intentional, but it does appear to be bugged. If possible, I would like an option to toggle autoplay on or off.

**Comment by salli20** [comment]
That coupled just be sure to him trying to make it as similar as possible to the official as when you first download that it is on

**Comment by CSab6482** [comment]
I found the auto play toggle in Settings > Playback. Thank you!

**Comment by windows-server-2003** [comment]
That's one solution, but the behavior was by design. The video playback is separated from video page(bottom screen), so that it won't suddenly switch to a new page while watching comments, etc.
